### PR TITLE
Use new clippy `disallowed_methods` syntax

### PR DESCRIPTION
**Pull request by klochowicz**
More clear in TOML file, hopefully will give better error messages as well.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Wait, why do we have two of these files? How does that actually behave? Are they merged together?

**Comment by klochowicz** [comment]
> Wait, why do we have two of these files? How does that actually behave? Are they merged together?

I think one of them concerned the workspace, the other one the `daemon` crate. I just upgraded them together. happy to merge them into one - which one would you prefer to keep?

**Comment by thomaseizinger** [comment]
> I think one of them concerned the workspace, the other one the `daemon` crate. I just upgraded them together. happy to merge them into one - which one would you prefer to keep?

I think I'd keep the workspace one!

**Comment by klochowicz** [comment]
> > I think one of them concerned the workspace, the other one the `daemon` crate. I just upgraded them together. happy to merge them into one - which one would you prefer to keep?
> 
> I think I'd keep the workspace one!

#1107

**Pull request merged**
