### PR TITLE
Move libp2p_connections_total to endpoint; add a new metric for connections by env/version

### LINKED ISSUE #2843: Move `NUM_LIBP2P_CONNECTIONS_GAUGE` to to the endpoint and create separate mertic for environment/version
At the moment we always increment upon receiving an `identify` message.

We should move this gauge into the `endpoint`, it is weird that it is in the responsibility of `identify` to record this metric. But at the moment the metric depends on additional information (wire version, daemon version, environment) that is not known to the endpoint but only received in the identify message. We can create a separate metric for recording the environment/version.

### PR DESCRIPTION
**Pull request by Restioson**
Fixes #2843.

I cannot yet verify that this works, since I can't seem to get prometheus to return anything for a query of just `libp2p_connections_total`, even on master, even although other metrics work.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
LGTM!

> I cannot yet verify that this works, since I can't seem to get prometheus to return anything for a query of just libp2p_connections_total, even on master, even although other metrics work.

I've never tried to consume metrics locally :(

**Comment by bonomat** [comment]
> Fixes #2843.
> 
> I cannot yet verify that this works, since I can't seem to get prometheus to return anything for a query of just `libp2p_connections_total`, even on master, even although other metrics work.

You can just call http://localhost:8001/api/metrics locally and see if this metric changes as you expect (i.e. if a taker connects and disconnects). No need to run prometheus :)

**Comment by Restioson** [comment]
> You can just call http://localhost:8001/api/metrics locally and see if this metric changes as you expect (i.e. if a taker connects and disconnects). No need to run prometheus :)

It's unfortunately absent from there too

**Comment by bonomat** [comment]
> It's unfortunately absent from there too

If it is missing, it means it was never set. Try to set it to 0 in the constructor (if we have something like this), it should atleast appear then.

**Review by bonomat — APPROVED** [review]
Seems to be working as expected: I started maker and taker locally and get this: 

image


taker terminates and it jumps down to 0 again

image

**Comment by Restioson** [comment]
Ah ok, thanks for testing it! I guess in that case it works :)

**Pull request merged**
