### PR TITLE
Remove introjs

### PR DESCRIPTION
**Pull request by bonomat**
If the intro is not shown, there is no way to use the application as there is an overlay which disables all interaction. 

I spend half a day debugging #2355 and can't figure it out.  I see no other option than removing it.

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
makes sense, at least we can continue moving forward until we fix the underlying issue.

Let's hope bors will pass as the taker-frontend job got stuck on CI...

**Comment by bonomat** [comment]
bors cancel

**Comment by bonomat** [comment]
Fixed a redundant import. Tests should pass now.

**Comment by bonomat** [comment]
looks good. 

bors r+

**Pull request merged**
