### PR TITLE
Update dependencies on all frontends

### PR DESCRIPTION
**Pull request by klochowicz**
1. Update yarn.lock on maker-frontend (has been out of dependabot for a long time). I've built and tested creating an offer, still works.
2. Add `maker-frontend` and `taker-electron` to dependabot monitoring

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
Even more dependabot spam :/

**Comment by klochowicz** [comment]
> Even more dependabot spam :/

we can consider alternatives! 

> Even more dependabot spam :/

I would probably not have dared to do so if we still needed to build & test the backend everytime when a JS dependency upgrades 😬

**Comment by bonomat** [comment]
I think we need to turn this down... 

image

**Pull request merged**
