### PR TITLE
Remove duplicate rollover received log

### PR DESCRIPTION
**Pull request by thomaseizinger**
This is already logged inside `rollover_maker::Actor`.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]

**Review by bonomat — APPROVED** [review]
👍

**Review by bonomat — COMMENTED** [review]
Actually, can we remove the other one, because here we have the `taker_id`

**Comment by thomaseizinger** [comment]
> Actually, can we remove the other one, because here we have the `taker_id`

I will add the taker_id to the other one. It makes more sense to have the log in the rollover actor and not in the maker_cfd actor.

**Review by bonomat — APPROVED** [review]
thanks :)

**Pull request merged**
