### PR TITLE
All the term to be configurable on the maker's commandline

### PR DESCRIPTION
**Pull request by thomaseizinger**
- Use the original order's term for rolling over
- Allow term to be configurable on the maker's commandline

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
boy that was easy :D

**Review by klochowicz — APPROVED** [review]

**Review by bonomat — APPROVED** [review]
👍

**Comment by bonomat** [comment]
I rebased for you @thomaseizinger

**Comment by bonomat** [comment]
I think it is important to keep in mind that the `term` should not be seen as a feature of a CFD. A CFD does not have an expiry (unlike options or a futures). A CFD never ends and hence does not have a term. This `term` here is an implementation necessity because we cannot have never ending CFDs with the features Bitcoin provides today.

**Comment by thomaseizinger** [comment]
> I think it is important to keep in mind that the `term` should not be seen as a feature of a CFD. A CFD does not have an expiry (unlike options or a futures). A CFD never ends and hence does not have a term. This `term` here is an implementation necessity because we cannot have never ending CFDs with the features Bitcoin provides today. 
> 

That is a good reminder, thank you! We should definitely word this accordingly. @da-kami @klochowicz something to keep in mind for the model make-over.

**Pull request merged**
