### PR TITLE
Let taker chose leverage

### LINKED ISSUE #1739: Let the taker choose leverage 1, 2 and 3
Leverage 2 is already the default, but we don't want to hard-code it anymore. See #1573.

Once #1573 is in, we can then let the taker choose a leverage from 1 to 3.

### LINKED ISSUE #1983: Dynamic computation of `initial_funding_fee`, `margin`, `liquidation_price`
At the moment the project assumes that we always have a leverage of 2 for the taker and 1 for the maker. 
This will change once we have selectable leverages.
At the moment, the projection uses the fixed known leverage to compute
- `initial_funding_fee`, 
- `margin`, 
- `liquidation_price`

If the taker can select a leverage in the UI, then these values will need to be calculated dynamically from the UI (or via an additional HTTP endpoint).

### PR DESCRIPTION
**Pull request by bonomat**
Resolves #1739 
Resolves #1983

### CODE REVIEW

**Review by da-kami — COMMENTED** [review]
I think the calculation of the margin and liquidation price according to the leverage is still missing. Merging this without the calculation does not make much sense to me.

**Comment by bonomat** [comment]
> I think the calculation of the margin according to the leverage is still missing. Merging this without the calculation does not make much sense to me.

There is a second ticket for this: https://github.com/itchysats/itchysats/issues/1983

**Comment by da-kami** [comment]
> > I think the calculation of the margin according to the leverage is still missing. Merging this without the calculation does not make much sense to me.
> 
> There is a second ticket for this: #1983

Ok, but I still think that activating this in the UI without implementing https://github.com/itchysats/itchysats/issues/1983 does not make sense. If we merge this the user will be able to select it, but the calculation update is missing.

**Comment by bonomat** [comment]
> > > I think the calculation of the margin according to the leverage is still missing. Merging this without the calculation does not make much sense to me.
> > 
> > 
> > There is a second ticket for this: #1983
> 
> Ok, but I still think that activating this in the UI without implementing #1983 does not make sense. If we merge this the user will be able to select it, but the calculation update is missing.

Fair enough, I'll add the other ticket into this PR to avoid merge conflicts.

**Comment by bonomat** [comment]
@da-kami : I've implemented the other ticket as well :)

**Review by da-kami — APPROVED** [review]
Great stuff!

I gave it a try locally also playing with allowing `x5` in the maker orders which results in a somewhat funny "bug" where the slider on the taker side allows `4` but that's actually not available. That's probably the problem of using a slider.

image

If we only plan to use 1, 2, 3 for now then I think we can merge, otherwise we should probably somehow fix this. Not sure the slider allows choices with different step intervals.

**Comment by bonomat** [comment]
> Great stuff!
> 
> I gave it a try locally also playing with allowing `x5` in the maker orders which results in a somewhat funny "bug" where the slider on the taker side allows `4` but that's actually not available. That's probably the problem of using a slider.
> 
> image
> 
> If we only plan to use 1, 2, 3 for now then I think we can merge, otherwise we should probably somehow fix this. Not sure the slider allows choices with different step intervals.

damn you were too fast :D , I noticed this bug as well and wanted to remove the `x5` again from the maker before anyone else notices it 😬
I don't think the slider allows steps with different intervals neither, so the alternative would just be to allow leverage 4 aswell

For now, we only want to support 1,2,3 anyway, so I'll remove the option from the maker.

**Comment by bonomat** [comment]
I've removed leverage `5` from the maker's UI because we don't want to support it

bors r+

**Pull request merged**
