### PR TITLE
Allow projection actor to retrieve latest Cfd state itself from DB

### PR DESCRIPTION
**Pull request by klochowicz**
Instead of retrieving Cfds inside Cfd actors, send a msg that they changed and
retrieve them by the projection actor itself.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice, thank you!

I think the two functions `cfd_actors` are pretty useless now so wouldn't mind inlining them :)

**Comment by klochowicz** [comment]
> Nice, thank you!
> 
> I think the two functions `cfd_actors` are pretty useless now so wouldn't mind inlining them :)

they're pretty small, but IMHO not useless! we had a problem previously that we forgot to update the feed in some cases... when we will move to looking at events in projection actor, then it will be useless - I agree :)

**Comment by thomaseizinger** [comment]
> Build failed:
> 
>     * [test_daemons (macos-latest)](https://github.com/itchysats/itchysats/runs/4405024373?check_suite_focus=true)

Well that is concerning:

> process didn't exit successfully: `/Users/runner/work/itchysats/itchysats/target/debug/deps/happy_path-795f3ae0e3f41528` (signal: 11, SIGSEGV: invalid memory reference)

How can our tests SEGFAULT??

**Review by luckysori — APPROVED** [review]

**Comment by klochowicz** [comment]
bors retry

**Comment by klochowicz** [comment]
> 
I have never seen a segfault on my macos, I suspect it might be some linked to the gh actions container.... is there any way to obtain a code dump from gh actions? 😅

**Comment by thomaseizinger** [comment]
> > 
> 
> I have never seen a segfault on my macos, I suspect it might be some linked to the gh actions container.... is there any way to obtain a code dump from gh actions? sweat_smile

I don't think so but it might be the same issue we saw on the Windows tests at times!

**Pull request merged**
