### PR TITLE
Update sqlx to 0.5.11

### LINKED ISSUE #1433: Upgrade sqlx dependency to released version
Step 1: Remove dependency on fork, now that https://github.com/launchbadge/sqlx/pull/1658 is merged.
Step 2: Update to released version once available.

### PR DESCRIPTION
**Pull request by rishflab**
closes #1433

### CODE REVIEW

**Comment by klochowicz** [comment]
perhaps we could pin the version of sqlx to `0.5.11` in both model and daemon? (not sure whether strictly needed due to `Cargo.lock` committed, but it would be more explicit)

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
> perhaps we could pin the version of sqlx to `0.5.11` in both model and daemon? (not sure whether strictly needed due to `Cargo.lock` committed, but it would be more explicit)

You mean in the `Cargo.toml`? I think we should set that to `0.5` to make it clear that cargo will bump patch versions.

**Comment by klochowicz** [comment]
> > perhaps we could pin the version of sqlx to `0.5.11` in both model and daemon? (not sure whether strictly needed due to `Cargo.lock` committed, but it would be more explicit)
> 
> You mean in the `Cargo.toml`? I think we should set that to `0.5` to make it clear that cargo will bump patch versions.

it's already 0.5. However, as we specifically wanted versions at least 0.5.11, I thought it could do no harm (dependabot would open a PR anyway about it). Not a blocker though :)

**Review by klochowicz — APPROVED** [review]

**Comment by klochowicz** [comment]
bors retry

**Pull request merged**
