### PR TITLE
Instrument spawned tasks as trace level follows_from

### PR DESCRIPTION
**Pull request by Restioson**
This should hopefully give better traceability on `level=trace`, but it is mostly to stop the spawned task from being included in the current one's time of execution.

This is a follow-up based on the information gained from #2411 - see the [following trace][1]:
image

The fact that the "Add fallible" span goes for so long tells me that the task is being included in it. By explicitly spawning the task as instrumented with a new span with no parent, this should fix the issue I think.

[1]: https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22traceId%22,%22minDuration%22:%225s%22,%22spanName%22:%22test%20span%20container%22,%22search%22:%22%22,%22query%22:%228a99ce72331d14128e98e9b3fef7a7b4%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
LGTM!

**Comment by Restioson** [comment]
Can this be borsed or does it need another review? If so, who should I request?

**Comment by klochowicz** [comment]
> Can this be borsed or does it need another review? If so, who should I request?

can be borsed, will do it now!

**Comment by Restioson** [comment]
Thanks!

**Pull request merged**
