### PR TITLE
Fix `payout_curve::calculate` dummy implementation

### PR DESCRIPTION
**Pull request by luckysori**
A compiler error slipped in #181. 

I also added an extra minor fix with https://github.com/comit-network/hermes/commit/62c8ffb65b796a7a41e76c91b947e20c0fe24530.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Thank you <3

**Comment by thomaseizinger** [comment]
bors ping

**Comment by da-kami** [comment]
bors ping

**Comment by da-kami** [comment]
we love you bors

**Pull request merged**
