### PR TITLE
chore: Bump sqlx to 0.6.2

### PR DESCRIPTION
**Pull request by klochowicz**
Bump sqlx-cli version to match new sqlx version and regenerate sqlx json file

### CODE REVIEW

**Comment by klochowicz** [comment]
@bonomat curiously, with everything bumped it doesn't want to recreate the json... anyway, we shouldn't get surprised again if the versions of sqlx and the CLI tool on CI are upgraded in lockstep.

**Review by luckysori — APPROVED** [review]

**Comment by bonomat** [comment]
> @bonomat curiously, with everything bumped it doesn't want to recreate the json... anyway, we shouldn't get surprised again if the versions of sqlx and the CLI tool on CI are upgraded in lockstep.

did you upgrade the cli locally?

**Comment by klochowicz** [comment]
> > @bonomat curiously, with everything bumped it doesn't want to recreate the json... anyway, we shouldn't get surprised again if the versions of sqlx and the CLI tool on CI are upgraded in lockstep.
> 
> did you upgrade the cli locally?

of course. checked twice, as I couldn't believe it. CI also didn't fail this time.

**Comment by bonomat** [comment]
> > > @bonomat curiously, with everything bumped it doesn't want to recreate the json... anyway, we shouldn't get surprised again if the versions of sqlx and the CLI tool on CI are upgraded in lockstep.
> > 
> > 
> > did you upgrade the cli locally?
> 
> of course. checked twice, as I couldn't believe it. CI also didn't fail this time.

lol

**Comment by klochowicz** [comment]
> > > > @bonomat curiously, with everything bumped it doesn't want to recreate the json... anyway, we shouldn't get surprised again if the versions of sqlx and the CLI tool on CI are upgraded in lockstep.
> > > 
> > > 
> > > did you upgrade the cli locally?
> > 
> > 
> > of course. checked twice, as I couldn't believe it. CI also didn't fail this time.
> 
> lol

I suspect it was due to `sqlformat` package having different versions (this is the only dep that changed with the upgrade).  🤷🏻‍♂️

**Pull request merged**
