### PR TITLE
Don't manually lock EncryptedJsonCodec

### PR DESCRIPTION
**Pull request by thomaseizinger**
There is a utility in `futures` for splitting anything that implements
`AsyncRead` + `AsyncWrite` into two components. It also uses a lock
interally but at least we don't have to implement it ourselves. In this
case, it also fixes using the wrong mutex (std::sync). A side-effect of
this change is that our codec now needs to have two type parameters
because we only construct it once and we have two different messages for
sending and receiving. The implications of this are minimal though.

Might help with #759.

### CODE REVIEW

**Review by rishflab — APPROVED** [review]
nice! that mutex was gross

**Review by klochowicz — APPROVED** [review]
great find! 👍 

as a side note, shall we completely ban usage of `std::sync::Mutex` as it can block the whole thread instead of just the future?

**Comment by thomaseizinger** [comment]
> as a side note, shall we completely ban usage of `std::sync::Mutex` as it can block the whole thread instead of just the future?

Yes that is a good idea!

**Pull request merged**
