### PR TITLE
Revert and some version bumps

### LINKED ISSUE #2840: taker-ui: tooltips have black background
This seems wrong

image

### PR DESCRIPTION
**Pull request by bonomat**
Reverts https://github.com/itchysats/itchysats/commit/1d68455c313ed6d1b1cb9cc08394b487b3936f52 and upgrades some of the versions manually. 

Looks like `@chakra-ui/react = ^2.3.1`  was the mean one

resolves https://github.com/itchysats/itchysats/issues/2840

Note: with this PR, running yarn dev for 
- taker: will start on `localhost:3000`
- maker: will start on `localhost:3001`

no more random flips depending on who starts first.

Looks good locally:

### CODE REVIEW

**Comment by bonomat** [comment]
I'm confused... the tests also fail on master ?!

**Review by luckysori — APPROVED** [review]

**Comment by klochowicz** [comment]
> I'm confused... the tests also fail on master ?!

where does it fail for you? I just ran the tests from master locally and they did not fail,

**Review by da-kami — APPROVED** [review]

**Comment by bonomat** [comment]
> > I'm confused... the tests also fail on master ?!
> 
> where does it fail for you? I just ran the tests from master locally and they did not fail,

Some random error. Google said use jest instead so I did 😅

**Comment by klochowicz** [comment]
> > > I'm confused... the tests also fail on master ?!
> > 
> > 
> > where does it fail for you? I just ran the tests from master locally and they did not fail,
> 
> Some random error. Google said use jest instead so I did 😅

perhaps it's due to some cruft in the yarn.lock file (there are some dependencies that are unmet, yarn spits out a warning after `yarn install`

**Pull request merged**
