### PR TITLE
Provide UI feedback for failed actions in the maker

### PR DESCRIPTION
**Pull request by klochowicz**
Taker PR will follow-up after potential issues get resolved.

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
sweet!

Were you able to test it in the UI?

**Comment by klochowicz** [comment]
> sweet!
> 
> Were you able to test it in the UI?

yes, I did - I've put an `anyhow::bail!` inside the post new order handler in the maker, and seen the toast coming up exactly as I expected 😃

**Comment by klochowicz** [comment]
earlier today my PR in `http-problem-api` got accepted, so we don't need to depend on the fork after all. I'll force-push with that fix.

**Pull request merged**
