### PR TITLE
Allow setting both short and long prices when creating an offer

### PR DESCRIPTION
**Pull request by klochowicz**
The price for maker going long is unused for now and only provided for the
future compatibility.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
ACK but why do we need to backport this?

**Comment by klochowicz** [comment]
> ACK but why do we need to backport this?

 soon we'll have to have one automation servicing two different maker versions and this will make sure that the API it interacts with can remain the same

**Comment by thomaseizinger** [comment]
> > ACK but why do we need to backport this?
> 
> soon we'll have to have one automation servicing two different maker versions and this will make sure that the API it interacts with can remain the same

Makes sense, thanks for the explanation!

**Comment by da-kami** [comment]
I am confused - this was pushed onto `release/0.4.4` by you @klochowicz or did I misunderstand something? 
Can this just be closed or pointed to master now?

**Comment by thomaseizinger** [comment]
> I am confused - this was pushed onto `release/0.4.4` by you @klochowicz or did I misunderstand something? Can this just be closed or pointed to master now?

Yes I think it was included :)

This can be re-targeted to master now AFAIK.

**Comment by da-kami** [comment]
I changed it to point to master

**Comment by klochowicz** [comment]
> > I am confused - this was pushed onto `release/0.4.4` by you @klochowicz or did I misunderstand something? Can this just be closed or pointed to master now?
> 
> Yes I think it was included :)
> 
> This can be re-targeted to master now AFAIK.

shouldn't we just merge the 0.4.4 changes into master instead? so that the changelog, version numbers etc all agrees?

**Comment by da-kami** [comment]
I expect the next release from `master` to be `0.5.0` - I think we will have breaking changes, so I would not bother too much aligning the version.

**Comment by klochowicz** [comment]
> I expect the next release from `master` to be `0.5.0` - I think we will have breaking changes, so I would not bother too much aligning the version.

I don't think that's an argument for not merging things done on a side branch into master?

**Comment by klochowicz** [comment]
I've opened a merge back from the released side branch: https://github.com/itchysats/itchysats/pull/1490

**Pull request closed without merging**
