### PR TITLE
Optimize culling query

### PR DESCRIPTION
**Pull request by bonomat**
We don't have to update events which are already null.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Good point!

**Review by da-kami — COMMENTED** [review]
Not sure this improvement is necessary - why would you keep a DLC without cets?

**Comment by da-kami** [comment]
> Not sure this improvement is necessary - why would you keep a DLC without cets?

Ah, it's the whole data field....?

**Comment by bonomat** [comment]
> > Not sure this improvement is necessary - why would you keep a DLC without cets?
> 
> Ah, it's the whole data field....?

it's an optimization to not run the query if the field was already removed in a former run.

**Comment by da-kami** [comment]
> > > Not sure this improvement is necessary - why would you keep a DLC without cets?
> > 
> > 
> > Ah, it's the whole data field....?
> 
> it's an optimization to not run the query if the field was already removed in a former run.

What confuses me is that you check against `dlc.cets` - I thought we are removing the complete previous `dlc` not just the `cets`. Maybe I missed that change.

**Comment by bonomat** [comment]
No, Lucas introduced a change which allowed us to remove the CETs: https://github.com/itchysats/itchysats/commit/1520dbcf408ebfc96068edaee5c181606629b7f3
We still keep the remaining info from the DLC.

**Comment by luckysori** [comment]
> No, Lucas introduced a change which allowed us to remove the CETs: [1520dbc](https://github.com/itchysats/itchysats/commit/1520dbcf408ebfc96068edaee5c181606629b7f3) We still keep the remaining info from the DLC.

Hmmm, we actually remove the entirety of the `dlc` field. We never look at the data once we roll over. I think we should check against `dlc` being null.

**Comment by bonomat** [comment]
What I said was bollocks. We indeed remove the full dlc field. 
Since the field `dlc` does not exist on `null` the query still works. But I you are right. Thanks for poitning it out @da-kami

**Pull request merged**
