### PR TITLE
Dynamically create matrix from workspace members

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
You must have fixed a bug, but I can't tell! This is a nice idea!

**Comment by thomaseizinger** [comment]
> You must have fixed a bug, but I can't tell! This is a nice idea!

What do you mean? I don't think I fixed any bug :)

**Comment by luckysori** [comment]
> What do you mean? I don't think I fixed any bug :)

I meant with your force push, a bug with the original implementation of this PR.

**Comment by thomaseizinger** [comment]
Now we only need a lint that checks that our `bors.toml` file is update to date.

**Pull request merged**
