### PR TITLE
Activate debug logs for `xtra_libp2p`

### PR DESCRIPTION
**Pull request by da-kami**
This helps understand what is going on in the endpoint. I think we need this inforamation for the time being. We can alternatively decide to set

### CODE REVIEW

**Review by bonomat — CHANGES_REQUESTED** [review]
It sounds like this is only for temporary use. If so, I'm against merging this PR and please use the environment variable to enable it:

```
RUST_LOG="xtra_libp2p=debug" 
```

Otherwise we have to push another release to disable it again. 

I would only put log filters here which force the log level higher as they would produce too much spam on debug otherwise.

**Comment by da-kami** [comment]
I can re-phrase is, I think we actually do always want to see this information. Otherwise we don't know enough about he connection.

**Comment by bonomat** [comment]
> I can re-phrase is, I think we actually do always want to see this information. Otherwise we don't know enough about he connection.

Wouldn't it be better to just export it as an environment variable?

**Comment by da-kami** [comment]
https://github.com/itchysats/cloud-conf/pull/83

**Pull request closed without merging**
