### PR TITLE
Don't store order in database

### LINKED ISSUE #657: Order and CFD model is entangled
Currently a `Cfd` _embeds_ an `Order` in our model.

This is causing problems (see #627) because an `Order` is immutable in our domain whereas a `Cfd` can get updated through roll-over. Ultimately, we need to untangle the two of them such that a `Cfd` _copies_ all necessary data from an `Order` upon creation so we can update it individually if we want to.

Note that "Update" here doesn't necessarily mean we use an `SQL UPDATE`. The current `Cfd` could still be a projection of multiple, immutable events (an event-sourcing-ish design) but even to support that, we need to untangle the `Order` from it to make it clear, where the information is coming from.

I would recommend tackling this by first enforcing privacy of a `Cfd`s fields (https://github.com/itchysats/itchysats/issues/646) because it will make this change much more contained and touch less areas of the codebase.

### PR DESCRIPTION
**Pull request by thomaseizinger**
Todo:

- [x] Needs manual testing

Tested opening a CFD locally. All fine.

### CODE REVIEW

**Comment by da-kami** [comment]
@itchymax @scratchscratchscratchy this wipes the DB again, is that OK or do we want a migration in this case?
The migration is possible but somewhat complex. If we decide to let the next release include the event sourcing DB changes already the migration is probably not worth it - because event sourcing cannot be migrated. We will have to wipe. 
So, the question for me would be: When is event sourcing gonna go into the DB?

**Review by thomaseizinger — COMMENTED** [review]
Thank you for finishing this!

**Review by klochowicz — APPROVED** [review]
nice refactor!

**Comment by da-kami** [comment]
Solving merge conflicts :)

**Pull request merged**
