### PR TITLE
Re-introduce library

### PR DESCRIPTION
**Pull request by luckysori**
If we want to write proper integration tests, we need to have a library crate.

---

Work towards #231.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Let's do it!

**Review by da-kami — APPROVED** [review]
image

**Comment by klochowicz** [comment]
> bors r+

third time lucky! 🪄

**Comment by luckysori** [comment]
> > bors r+
> 
> third time lucky! magic_wand

At this point I'm trying to physically shove it into master.

**Comment by luckysori** [comment]
Thank you to our overlord `bors`.

**Pull request merged**
