### PR TITLE
Umbrel seed 

### LINKED ISSUE #978: Provide seed as argument
Umbrel exposes `$APP_SEED` which is a hex hex string deterministically derived from the users Umbrel seed. We could make use of this. It would mean that if a user's Umbrel broke and they setup a new one and imported their previous Umbrel seed, the ItchySats app would then derive the same wallet as the previous install and recover the previous funds.

_Originally posted by @lukechilds in https://github.com/getumbrel/umbrel/issues/1149#issuecomment-1001552559_

### PR DESCRIPTION
**Pull request by rishflab**
Implements #978 for 0.3.x

### CODE REVIEW

**Comment by bonomat** [comment]
Let's do not merge into 0.3.5 but once approved create 0.3.6 and take the commit. That way we preserve version 0.3.5 as a branch

**Review by da-kami — APPROVED** [review]
looks good - I think we could even merge this into master and then backport the commit to `0.3.6`. I don't think it touches any code that changed. But feel free to do it the other way round.

**Comment by da-kami** [comment]
@rishflab I noticed that release `0.3.6` is alrady out. Should we point this against master now to get it into the current version as well or is there a different plan?

**Comment by rishflab** [comment]
> @rishflab I noticed that release `0.3.6` is alrady out. Should we point this against master now to get it into the current version as well or is there a different plan?

yep, ill rebase  and merge it onto master today. I was not sure how to deal with this PR with this new backporting workflow.

**Comment by da-kami** [comment]
It seems you are pointing all backported commits against master now. You'll have to remove the ones that are not relevant for your changes :)

**Comment by thomaseizinger** [comment]
As part of this, can we also rip out the reinit feature for the wallet please? It is not needed anymore!

**Comment by rishflab** [comment]
> As part of this, can we also rip out the reinit feature for the wallet please? It is not needed anymore!

I am not sure we should remove it. I think it is still a nice feature to have and we will probably want it in the medium to longterm.
I think we should have a quick discussion on how we deal with the backup problem longterm.

**Comment by thomaseizinger** [comment]
> I am not sure we should remove it. I think it is still a nice feature to have and we will probably want it in the medium to longterm.

I would like to have it removed because it is dead code at the moment and annoying to maintain!
If we want such a feature again in the future, we can add it on top of whatever the code is then!

**Comment by da-kami** [comment]
Is this rebased on latest master? If so we should record the test failure:

```
failures:

---- open_cfd_is_refunded stdout ----
Jan 10 05:43:02.881  INFO happy_path::harness: Running version: 0.3.0
Jan 10 05:43:02.898  INFO daemon::maker_inc_connections: Listening on 127.0.0.1:33565
Jan 10 05:43:02.899 DEBUG daemon: Maker actor system ready
Jan 10 05:43:02.915 DEBUG daemon: Taker actor system ready
Jan 10 05:43:02.916 DEBUG daemon::connection: No connection to the maker
Jan 10 05:43:02.916 DEBUG daemon::connection: Connecting to maker address=127.0.0.1:33565
Jan 10 05:43:02.921  INFO daemon::maker_inc_connections: Upgrade new connection taker_address=127.0.0.1:48686
Jan 10 05:43:02.927 DEBUG daemon::noise: Noise protocol responder handshake is complete
Jan 10 05:43:02.929 DEBUG daemon::noise: Noise protocol initiator handshake is complete
Jan 10 05:43:02.930  INFO daemon::maker_inc_connections: Connection upgrade successful taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501 taker_address=127.0.0.1:48686
Jan 10 05:43:02.931 TRACE wire: Sending CurrentOrder taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:02.932 TRACE wire: Sending Heartbeat taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:02.932 TRACE wire: Sent heartbeat message. Sleeping for 60
Jan 10 05:43:02.933  INFO daemon::connection: Established connection to maker address=127.0.0.1:33565
Jan 10 05:43:02.934 TRACE wire: Received CurrentOrder
Jan 10 05:43:02.934 TRACE wire: measuring heartbeat pulse
Jan 10 05:43:02.934 TRACE wire: Received Heartbeat
Jan 10 05:43:02.935 TRACE wire: Sending CurrentOrder taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:02.936 TRACE wire: Received CurrentOrder
Jan 10 05:43:02.936  INFO daemon::taker_cfd: Taking current order: Order { id: OrderId(Hyphenated(a7317e7d-0aee-45de-b01c-d2fa0e864e80)), trading_pair: BtcUsd, position: Short, price: Price(50000), min_quantity: Usd(5), max_quantity: Usd(100), leverage: Leverage(2), liquidation_price: Price(33333.333333333333333333333333), creation_timestamp: Timestamp(1641793382), settlement_interval: Duration { seconds: 86400, nanoseconds: 0 }, origin: Theirs, oracle_event_id: BitMexPriceEventId { timestamp: OffsetDateTime { utc_datetime: PrimitiveDateTime { date: Date { year: 2022, ordinal: 11 }, time: Time { hour: 6, minute: 0, second: 0, nanosecond: 0 } }, offset: UtcOffset { hours: 0, minutes: 0, seconds: 0 } }, digits: 20 }, fee_rate: 1 }
Jan 10 05:43:02.938 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:02.938 TRACE wire: Sending TakeOrder
Jan 10 05:43:02.939 TRACE wire: Received TakeOrder taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:02.939 DEBUG daemon::maker_cfd: Taker wants to take an order taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501 quantity=5 order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:02.939 TRACE wire: Sending CurrentOrder taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:02.941 TRACE wire: Received CurrentOrder
Jan 10 05:43:02.942 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:03.941 DEBUG daemon::maker_cfd: Maker accepts order order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:03.941  INFO daemon::setup_maker: Maker accepts an order order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:03.941 TRACE wire: Sending ConfirmOrder taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:03.944 TRACE wire: Received ConfirmOrder
Jan 10 05:43:03.944  INFO daemon::setup_taker: Order got accepted order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:03.946 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:04.754 TRACE wire: Sending Protocol
Jan 10 05:43:04.761 TRACE wire: Received Protocol taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:04.767 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:43:05.578  INFO daemon::setup_contract: Exchanged setup parameters
Jan 10 05:43:19.196  INFO daemon::setup_contract: Created CFD transactions
Jan 10 05:43:19.269 TRACE wire: Sending Protocol taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:19.272 TRACE wire: Sending Protocol taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:43:20.041 TRACE wire: Received Protocol
Jan 10 05:43:20.041  INFO daemon::setup_contract: Exchanged setup parameters
Jan 10 05:43:33.625  INFO daemon::setup_contract: Created CFD transactions
Jan 10 05:43:33.699 TRACE wire: Sending Protocol
Jan 10 05:43:35.026 TRACE wire: Received Protocol
Jan 10 05:43:35.026  INFO daemon::setup_contract: Exchanged CFD transactions
Jan 10 05:44:30.317  INFO daemon::setup_contract: Verified all signatures
Jan 10 05:44:30.318 TRACE wire: Sending Protocol
Jan 10 05:44:30.878 TRACE wire: Received Protocol taker_id=b1e98ecbb518ab75813b44fc059cbd214fe83fd3e8264df2517654e030b53501
Jan 10 05:44:30.880 ERROR daemon::model::cfd: Contract setup failed: Expected Msg1 within 70 seconds: deadline has elapsed
Jan 10 05:44:30.883 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
Jan 10 05:45:02.935 TRACE wire: measuring heartbeat pulse
Jan 10 05:45:40.322 ERROR daemon::model::cfd: Contract setup failed: Expected Msg2 within 70 seconds: deadline has elapsed
Jan 10 05:45:40.323 DEBUG daemon::projection: Unable to calculate profit/loss without current price order_id=a7317e7d-0aee-45de-b01c-d2fa0e864e80
thread 'open_cfd_is_refunded' panicked at 'assertion failed: `(left == right)`
  left: `SetupFailed`,
 right: `PendingOpen`: unexpected cfd state in the taker', daemon/tests/happy_path.rs:392:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    open_cfd_is_refunded
```

**Pull request merged**
