### PR TITLE
Add dprint plugin to format yaml files

### PR DESCRIPTION
**Pull request by klochowicz**
I've derisked the runtime cost and wrote about it in the commit message (unnoticeable on my machine, please check on yours if you're worried about this). 

If this gets approved, I'm happy to roll it out to our other repos.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Concept ACK although I'd suggest to squash the two commits together.

**Comment by klochowicz** [comment]
> Concept ACK although I'd suggest to squash the two commits together.

sure, will do!

**Review by thomaseizinger — APPROVED** [review]
OCD says LGTM

**Review by luckysori — APPROVED** [review]
Yay for autoformatting. Thanks!

**Pull request merged**
