### PR TITLE
fix (projection): Start projection actor for taker

### LINKED ISSUE #2760: ETHUSD: Long and short liquidation price are swapped
In addition to https://github.com/itchysats/itchysats/issues/2754 we should check how we compute the liquidation prices. Right now they are swapped: 

Long position shows short liquidation price and vice versa: 

image

image

### PR DESCRIPTION
**Pull request by bonomat**
supersedes: https://github.com/itchysats/itchysats/pull/2810

resolves https://github.com/itchysats/itchysats/issues/2760

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Nooooooooooooooooooooooo, sorry to waste your time.

**Review by klochowicz — APPROVED** [review]
🙈

**Comment by klochowicz** [comment]
> Nooooooooooooooooooooooo, sorry to waste your time.

@luckysori this at least prompted us to add assertions in the actor tests that should have caught such thing in the first place. I see it as a testament that we haven't written enough tests!

**Comment by luckysori** [comment]
> > Nooooooooooooooooooooooo, sorry to waste your time.
> 
> @luckysori this at least prompted us to add assertions in the actor tests that should have caught such thing in the first place. I see it as a testament that we haven't written enough tests!

I agree that it motivated some good things, but it's interesting that I think the tests would have passed because we initialise the `projection::Actor`s correctly in `daemon-tests`:

https://github.com/itchysats/itchysats/blob/d1cc143f245329a7b8692ee6e3409beb40fd23a5/daemon-tests/src/lib.rs#L734-L740

https://github.com/itchysats/itchysats/blob/d1cc143f245329a7b8692ee6e3409beb40fd23a5/daemon-tests/src/lib.rs#L941-L947

**Comment by bonomat** [comment]
yes, that's the fun part. The tests work because they initialize the actor themselves 😅

**Comment by bonomat** [comment]
bors +

**Comment by klochowicz** [comment]
> yes, that's the fun part. The tests work because they initialize the actor themselves 😅

OMG. that would be pretty hard to spot indeed. maybe we could add checks in grafana for sanity of some values in our testnet taker?

**Pull request merged**
