### PR TITLE
Remove margin calc endpoint

### PR DESCRIPTION
**Pull request by thomaseizinger**
This is a breaking API change but only on the taker and we control the only client for that atm.

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
I think this PR should remove `MarginRequestPayload` and `MarginResponse` from taker UI's `types.ts`

This somewhat breaks our paradigm of doing no calculations in the UI, but it simplifies handling the margin and cost calc. I will see to rebase my work on it.

**Comment by thomaseizinger** [comment]
> This somewhat breaks our paradigm of doing no calculations in the UI, but it simplifies handling the margin and cost calc. I will see to rebase my work on it.

I agree but they are at least very simple calculations and for display purposes only.

**Comment by thomaseizinger** [comment]
> I think this PR should remove `MarginRequestPayload` and `MarginResponse` from taker UI's `types.ts`

Done.

**Pull request merged**
