### PR TITLE
Produce a single binary for integration tests

### PR DESCRIPTION
**Pull request by klochowicz**
If we have multiple files here, they end up in different test binaries.
This means that we have to link everything separately.
And linking so much is slow (and likely single-threaded).

See: https://endler.dev/2020/rust-compile-times/#combine-all-integration-tests-in-a-single-binary

### CODE REVIEW

**Comment by klochowicz** [comment]
@da-kami I overlooked this when you asked in your old PR (splitting them in modules was still a great thing then!)

**Review by Restioson — APPROVED** [review]

**Comment by Restioson** [comment]
The variance in compile times in CI is quite high; could we verify this locally that it does make a difference?

**Comment by bonomat** [comment]
The test execution time in this PR went up big times. Are you sure this has the effect you were aiming for?

**Review by da-kami — COMMENTED** [review]
I agree with the other comments: It would be great to verify, at least locally, that this change has the effect we expect.

**Comment by luckysori** [comment]
> The test execution time in this PR went up big times. Are you sure this has the effect you were aiming for?

It could be that we can't parallelise the tests after this change.

**Comment by Restioson** [comment]
> It could be that we can't parallelise the tests after this change.

The tests from even one binary would be run in parallel by `cargo test`, but since we are using nextest now that might change things. `tokio::test` might affect it too.

> I agree with the other comments: It would be great to verify, at least locally, that this change has the effect we expect.

I am going to give this a shot locally

**Comment by Restioson** [comment]
All tests run as follows: 

```sh
$ cargo clean # If a clean compile
$ time cargo test --workspace --no-run
```

Sccache was enabled for all runs. To create the incremental scenario, I just added a comment to daemon/lib.rs. I rebased this on master before running to get the best possible comparison (the branch is currently 45 commits behind master, as of time of writing).

Master clean:
```
real	2m52.356s
user	18m10.048s
sys	4m0.176s
```

Master incremental:
```
real	1m20.116s
user	6m33.288s
sys	2m37.488s
```

This branch clean:
```
real	2m55.334s
user	19m43.344s
sys	4m26.928s
```

This branch incremental:
```
real	1m27.605s
user	7m24.617s
sys	3m2.406s
```

So, this is currently a regression. However, I think this is because the current branch does not achieve the intended outcome. The logs print the following:
```
 Executable tests/connectivity.rs (target/debug/deps/connectivity-a2679c5a44542575)
  Executable tests/liquidation.rs (target/debug/deps/liquidation-99e14f843514c389)
  Executable tests/main.rs (target/debug/deps/main-16fa08f329890e08)
  Executable tests/non_collaborative_settlement.rs (target/debug/deps/non_collaborative_settlement-31ccb492b6a0e780)
  Executable tests/offer.rs (target/debug/deps/offer-689477e0a8ee25f2)
  Executable tests/order.rs (target/debug/deps/order-fc9853034d2b5fb0)
  Executable tests/refund.rs (target/debug/deps/refund-6966992ea151647c)
  Executable tests/rollover.rs (target/debug/deps/rollover-55d6db48d6dc052f)
```

This seems to imply that this hasn't had the intended effect of combining the tests into one binary, but rather created one extra, grouped test binary `main`.

**Comment by Restioson** [comment]
We can achieve the desired effect by moving everything in `daemon-tests/tests/` into a subfolder called `main`. This yields the following results.

Clean:
```
real	1m55.709s
user	9m15.758s
sys	1m55.161s
```

Incremental:
```
real	0m56.363s
user	2m21.795s
sys	0m43.918s
```

This is much better than master.

**Comment by Restioson** [comment]
Now, on to the run times. I ran `time cargo nextest run --profile ci` after building.

Master:
```
real	3m14.394s
user	23m55.672s
sys	0m5.129s
```

For some reason, master wanted to recompile some stuff *again* after I compiled the tests from clean, so I let it do that and then ran the nextest. 

This branch, with my changes:
```
real	3m1.341s
user	21m24.211s
sys	0m3.933s
```

So, this is a slight win, on paper. However, one test failed on master and was rerun, so I'd count this as overall no net change.

**Comment by klochowicz** [comment]
closed in favour of #2605

**Comment by klochowicz** [comment]
@Restioson thanks for your findings! I've squashed the 2 commits, marked you as a co-author, and rebased on master. hopefully someone can bors it tomorrow if it gets the necessary approvals :)

**Review by Restioson — APPROVED** [review]

**Review by luckysori — APPROVED** [review]
I'm excited to try this out!

One question: do we know why it's necessary to create a `main` submodule?

**Comment by Restioson** [comment]
> One question: do we know why it's necessary to create a main submodule?

If you mean the whole folder thing, this is so that the children do not automatically become their own test target.

**Review by da-kami — APPROVED** [review]
I will rebase and bors this!

**Pull request merged**
