### PR TITLE
Merge back 0.5.5 patch release

### PR DESCRIPTION
**Pull request by klochowicz**
Without this, we don't get the tag on master, and the latest HEAD indicates that we're running an outdated version.

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
0 changes?

**Review by luckysori — COMMENTED** [review]
I understand the need to merge back the tag, but I don't get exactly how this works. 

Release 0.5.5 was a patch release on top of 0.5.4, where a few commits were cherry-picked from master. They are still in master, but in a different order. How can this tag go back into master at all?

**Comment by klochowicz** [comment]
> I understand the need to merge back the tag, but I don't get exactly how this works.
> 
> Release 0.5.5 was a patch release on top of 0.5.4, where a few commits were cherry-picked from master. They are still in master, but in a different order. How can this tag go back into master at all?

the idea is that this makes the tag reachable from `master` branch, and I can see this fixes both my magit view as the annoying popup where latest HEAD was "not the latest version" :P 
I'm not a git expert by any means though, so I can't comment more. Maybe there is a better way.

**Comment by klochowicz** [comment]
> 0 changes?

yes, because all of the changes happened to already be included on master.

**Pull request merged**
