### PR TITLE
Disable leverage slider

### PR DESCRIPTION
**Pull request by thomaseizinger**
Before:

image

After:

image

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
👍

**Review by da-kami — APPROVED** [review]
How about adding a tooltip that explains that this is fixed to `2` at the moment?
I think it is confusing to the user if we don't state that it cannot be changed at the moment, users might expect that they "have to do something" so it can be changed...

**Comment by thomaseizinger** [comment]
> How about adding a tooltip that explains that this is fixed to `2` at the moment? I think it is confusing to the user if we don't state that it cannot be changed at the moment, users might expect that they "have to do something" so it can be changed...

Done!

image

**Review by da-kami — APPROVED** [review]

**Pull request merged**
