### PR TITLE
Upgrade tracing-subscriber to 0.3

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
thanks! nice preparation for using some external log tool, and great write-up socialising the details of removing `chrono`.

**Comment by klochowicz** [comment]
@thomaseizinger I think you might need to rebase on latest `origin/master`? unfortunately, we might need to do that with all the PRs that got created before "block-fixup" got in....

**Comment by thomaseizinger** [comment]
> @thomaseizinger I think you might need to rebase on latest `origin/master`? unfortunately, we might need to do that with all the PRs that got created before "block-fixup" got in....

Yep you are right!

**Comment by klochowicz** [comment]
> > @thomaseizinger I think you might need to rebase on latest `origin/master`? unfortunately, we might need to do that with all the PRs that got created before "block-fixup" got in....
> 
> Yep you are right!

> > @thomaseizinger I think you might need to rebase on latest `origin/master`? unfortunately, we might need to do that with all the PRs that got created before "block-fixup" got in....
> 
> Yep you are right!

I was just about to tell everyone that they should rebase their PRs, but you seem to be the sole author of all unmerged PRs 😁

**Comment by thomaseizinger** [comment]
cc @bonomat:

https://github.com/itchysats/itchysats/pull/1144/commits/1a71bcbf9d8b7728ffb4410993459c289053248a changes the timestamp in the JSON logs to RFC3339 formatting. Not sure if we use the JSON logs anywhere but this is something to be aware of and should make parsing these logs easier.

**Pull request merged**
