### PR TITLE
Disable more of the otel_test macro according to env var

### LINKED ISSUE #2473: CI test run times can be really long
We had a CI `macos` test run that took `15` minutes to complete! 
I don't think it is expected that CI takes *that* long.

See: https://github.com/itchysats/itchysats/runs/7407394638?check_suite_focus=true on https://github.com/itchysats/itchysats/pull/2469

### PR DESCRIPTION
**Pull request by Restioson**
Maybe fixes #2473

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
That second definitely added up. Thanks :)

**Comment by bonomat** [comment]
As you can see from here: https://github.com/itchysats/itchysats/runs/7424358882?check_suite_focus=true

it's a bit faster: ~13 minutes

**Comment by Restioson** [comment]
Hmm, that's still quite a bit slower than before...

**Review by klochowicz — APPROVED** [review]
thanks, at least it makes it a bit more bearable :)

**Comment by klochowicz** [comment]
I'll go ahead and merge this, as it shaves a few minutes of each CI run.

**Pull request merged**
