### PR TITLE
Test release build on the CI

### PR DESCRIPTION
**Pull request by klochowicz**
Verify whether the actor tests on the CI fail the same way on the release build.

I also wanted to check whether it's feasible at all (how much time will it take to build using github).

### CODE REVIEW

**Comment by klochowicz** [comment]
I managed to trim it to ~9mins, not sure whether that is acceptable or not. Opening the floor for discussions :)

**Comment by thomaseizinger** [comment]
I think you could easily make this part of the existing matrix to avoid the duplicate declaration.

However, I am not sure we need this specifically?

**Comment by klochowicz** [comment]
> I think you could easily make this part of the existing matrix to avoid the duplicate declaration.
> 
> However, I am not sure we need this specifically?

Trying to avoid one more declaration would result in longer build times - we don't need to do another smoke test etc. This trade-off seemed more worthy IMHO.

The idea behind it was being able to verify that some of our failures in CI *only* ever happen in debug mode. This is as such an useful data point when considering whether something has an impact on the released version - in general, it makes sense to also test the version that the users are actually using).

The counter-argument was that this would significantly increase build times on the CI - this PR was submitted as draft to analyse by how much we'd increase it. From looking at preliminary results, it's almost the same times.

**Comment by thomaseizinger** [comment]
> Trying to avoid one more declaration would result in longer build times - we don't need to do another smoke test etc. This trade-off seemed more worthy IMHO.

How much longer would the build times be? We should be able to cut the build times down by splitting out crates. See https://github.com/itchysats/itchysats/issues/226.

> This is as such an useful data point when considering whether something has an impact on the released version - in general, it makes sense to also test the version that the users are actually using).

Shouldn't we be doing a smoke-test then? :)

**Comment by thomaseizinger** [comment]
Overall, I'd appreciate if we use GitHub's build-matrix as much as possible. It would also be nice to not special case the arm build and use a self-hosted GitHub actions runner that uses an ARM cloud machine to run the tests.

**Review by luckysori — APPROVED** [review]

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
I opened https://github.com/itchysats/itchysats/issues/1096.

**Comment by thomaseizinger** [comment]
If you want these jobs to be required for bors to merge the PR, make sure you edit `bors.toml` accordingly.

**Comment by klochowicz** [comment]
> > Trying to avoid one more declaration would result in longer build times - we don't need to do another smoke test etc. This trade-off seemed more worthy IMHO.
> 
> How much longer would the build times be? We should be able to cut the build times down by splitting out crates. See #226.
> 
> > This is as such an useful data point when considering whether something has an impact on the released version - in general, it makes sense to also test the version that the users are actually using).
> 
> Shouldn't we be doing a smoke-test then? :)

Smoke test is unlikely to give us any difference - the debug builds would differ mainly with optimisations used and lack of debug assertions etc. I don't mind having one for correctness.

**Pull request merged**
