### PR TITLE
Replace TODOs with GitHub issue

### PR DESCRIPTION
**Pull request by luckysori**
See https://github.com/itchysats/itchysats/issues/1094. This is one of the issues that were mentioned before, @rishflab.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Review by klochowicz — COMMENTED** [review]
hm, without these TODOs  it will be harder to find all places by the person trying to fix this issue - not sure whether this is worth it, especially that there's virtually no risk of this lingering? 

Totally agree that there should have been an gh issue raised at the time this got merged to master though.

**Comment by luckysori** [comment]
> hm, without these TODOs it will be harder to find all places by the person trying to fix this issue - not sure whether this is worth it, especially that there's virtually no risk of this lingering?
> 
> Totally agree that there should have been an gh issue raised at the time this got merged to master though.

I understand your point, but the TODO noise is annoying me in the codebase atm. What if I permalink to the 3 places where the fix needs to occur in the GH issue?

**Comment by klochowicz** [comment]
> > hm, without these TODOs it will be harder to find all places by the person trying to fix this issue - not sure whether this is worth it, especially that there's virtually no risk of this lingering?
> > Totally agree that there should have been an gh issue raised at the time this got merged to master though.
> 
> I understand your point, but the TODO noise is annoying me in the codebase atm. What if I permalink to the 3 places where the fix needs to occur in the GH issue?

I think that there problem with the TODOs is happening because a lot of them are "someday/maybe" and these ones should be pruned without any hesitation. However, in this particular case, the task in one of our next tasks, potentially being actioned today (and definitely in the near future) - I don't get why make it harder for the assignee. 

If I was assigned, I would be grateful for these TODOs being left, and permalinks would be an annoying overhead as I would need to jump out of my IDE.

There is also the point that as per our latest agreement TODOs should not be in the code - I'm happy with you push this as it's valid from this point of view, but this PR made me think that perhaps we should relax this requirement (I'll raise a discussion at the next opportunity :) )

PS in this case it should be actually a `FIXME` 😅  (we know we're doing something wrong and it should have been fixed).

**Comment by luckysori** [comment]
> There is also the point that as per our latest agreement TODOs should not be in the code - I'm happy with you push this as it's valid from this point of view, but this PR made me think that perhaps we should relax this requirement (I'll raise a discussion at the next opportunity :) )

I just assumed that we had already chosen to relax or ignore that agreement, since the number of TODOs doesn't seem to be going down.

I'll close this PR because it doesn't seem to be adding any value at the moment, but I will keep trying to remove TODOs if I get the chance.

**Comment by klochowicz** [comment]
> > There is also the point that as per our latest agreement TODOs should not be in the code - I'm happy with you push this as it's valid from this point of view, but this PR made me think that perhaps we should relax this requirement (I'll raise a discussion at the next opportunity :) )
> 
> I just assumed that we had already chosen to relax or ignore that agreement, since the number of TODOs doesn't seem to be going down.
> 
> I'll close this PR because it doesn't seem to be adding any value at the moment, but I will keep trying to remove TODOs if I get the chance.

OK, I'll try to keep vigilant of meaningless TODOs too, so that the signal to noise ratio improves. Found a few now #1098 :)

**Pull request closed without merging**
