### PR TITLE
Add cargo-bloat CI action to determine bloat increase in new PRs

### PR DESCRIPTION
**Pull request by klochowicz**
This way we can make an informed decision whether additional bloat / binary size
in a new PR is acceptable or not.

### CODE REVIEW

**Comment by bonomat** [comment]
It looks like this is still a draft and you are testing? If so, can you use a fork when you test new CI actions please. That way it does not block other CI actions in this repository.

**Comment by klochowicz** [comment]
> It looks like this is still a draft and you are testing? If so, can you use a fork when you test new CI actions please. That way it does not block other CI actions in this repository.

of course, I can do this! sorry if it caused problems, I thought that if an action gets added in the PR it does not have affect on others, as it's not pushed to the main repo.

**Comment by klochowicz** [comment]
migrated to my fork until it's ready: https://github.com/klochowicz/hermes/pull/1

**Comment by bonomat** [comment]
> of course, I can do this! sorry if it caused problems, 

You didn't :)

**Pull request closed without merging**
