### PR TITLE
Simplify UI

### PR DESCRIPTION
**Pull request by thomaseizinger**
UI now looks like this when it doesn't have a lot of space:

image

But also looks decent when it does have a lot of space:

Screenshot from 2021-09-23 13-43-20

### CODE REVIEW

**Comment by klochowicz** [comment]
I like getting rid of the 3 tabs - they weren't used at all! 👍 

Is there a reason why the tiles don't look like tiles anymore - perhaps you could return to the 2 columns in the grid approach? They seem way too big now.

**Comment by thomaseizinger** [comment]
> Is there a reason why the tiles don't look like tiles anymore - perhaps you could return to the 2 columns in the grid approach? They seem way too big now.

Scaling things horizontally is difficult in my experience if you want things to be somewhat responsive.
Also I find lists easier to understand because my eyes don't have to go left and right :)

**Review by da-kami — APPROVED** [review]
Good enough as foundation for now.
I expect the UI to change more radical once we get user feedback.

**Comment by thomaseizinger** [comment]
> Good enough as foundation for now.
> I expect the UI to change more radical once we get user feedback.

Agreed which is why I wanted to make it simpler.

**Pull request merged**
