### PR TITLE
Colour terminal output on the CI

### PR DESCRIPTION
**Pull request by klochowicz**
Spotted somewhere in nextest examples.

### CODE REVIEW

**Review by bonomat — APPROVED** [review]

**Review by holzeis — APPROVED** [review]

**Review by luckysori — APPROVED** [review]
LGTM but no idea why CI fails.

**Review by Restioson — APPROVED** [review]
CI fail is weird - seems to be a yarn cache issue?

**Comment by da-kami** [comment]
As weird as it is this error is persistently happening on retries. I just retried the failed tasks twice with the same result. 
I think this is the problem: https://github.com/yarnpkg/yarn/issues/5945

**Comment by luckysori** [comment]
> As weird as it is this error is persistently happening on retries. I just retried the failed tasks twice with the same result. I think this is the problem: [yarnpkg/yarn#5945](https://github.com/yarnpkg/yarn/issues/5945)

Nice find! Let's drop the second commit then.

**Pull request merged**
