### PR TITLE
Show order id in maker-ui and taker-ui

### PR DESCRIPTION
**Pull request by bonomat**
This can come handy for faster debugging

image

image

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Maybe we could do the same for the taker UI when we're not building on release.

**Comment by bonomat** [comment]
I think it can be specifically handy on a release build (our testnet is running on release builds). 

Hence, I've added a simple toggle: things are a bit jumpy but I think this is fine for this :)

image


image

**Review by klochowicz — APPROVED** [review]
I love how discrete and non-intrusive this additional info is on the taker side, even when enabled.

useful and tasteful change 🥇

**Comment by bonomat** [comment]
> I love how discrete and non-intrusive this additional info is on the taker side, even when enabled.
> 
> useful and tasteful change 🥇

I take that ☺️

bors r+

**Pull request merged**
