### PR TITLE
Depend on cfd protocol from `maia` repository

### PR DESCRIPTION
**Pull request by klochowicz**
Cfd protocol got moved into a separate repository.
All references of `cfd_protocol` were renamed to `maia`.

Patch cargo.toml with a fixed git revision until it gets a public release.

### CODE REVIEW

**Review by bonomat — APPROVED** [review]
Fixed the formatting for you ;)

**Comment by klochowicz** [comment]
> Fixed the formatting for you ;)

cheers, I was out for lunch and didn't notice :)

**Comment by da-kami** [comment]
I think this will require a manual rebase on master, seems bors is unhappy

**Review by da-kami — APPROVED** [review]

**Comment by da-kami** [comment]
Sorry for my earlier comment, I think the rebase was actually not needed. bors' failure was related to the smoke test being flaky 😬

**Comment by klochowicz** [comment]
> I think this will require a manual rebase on master, seems bors is unhappy

rebased the branch and pushed again. let's hope it works this time :)

**Pull request merged**
