### PR TITLE
Reorganise crates inside the workspace

### PR DESCRIPTION
**Pull request by klochowicz**
Move all the crates into a dedicated `crates` directory.
This makes it simpler to add/remove crate from the workspace (no need to
maintain a list), and also makes it much easier to find other things inside
the repository, which are not rust crates.

### CODE REVIEW

**Review by bonomat — COMMENTED** [review]
Does not seem to be necessary to me.

**Review by luckysori — COMMENTED** [review]
I personally don't need this. If other people like it then we can give it a go.

**Comment by klochowicz** [comment]
maybe a bit more explanation: when new people get onboarded to the project, especially new to Rust, it's hard to find yourself in the project with over 30 directories in its root (especially 

This way we have a logical split between:
- rust crates
- docs
- target dir
- frontend dirs
- `mainnet`/`testnet` dirs (outcome of running the program).

We had to go through each directory last time when onboarding as the present accidental structure can be confusing, and I feel that we could do better. To me this is an effortless step in the right direction (still flat structure of the crates, but they're "contained" in a single directory).

To illustrate:

* Before
```
  CHANGELOG.md           TODOs.org_archive      jaeger.sh              rust-toolchain.toml    xtra-bitmex-price-feed
CONTRIBUTING.md        bdk-ext                mainnet                shared-bin             xtra-libp2p
CRATE-STRUCTURE.md     bitmex-stream          maker                  sqlite-db              xtra-libp2p-offer
Cargo.lock             bors.toml              maker-frontend         start_all.sh           xtra-libp2p-ping
Cargo.toml             btsieve                model                  taker                  xtra-libp2p-rollover
Dockerfile             clippy.toml            otel-tests             taker-frontend         xtras
FAQ.md                 daemon                 otel-tests-macro       target
LICENSE                daemon-tests           quiet-spans            testnet
README.md              docs                   rocket-basicauth       tokio-extras
TODOs.org              dprint.json            rust-embed-rocket      vergen-version
```

* After
```
  CHANGELOG.md        Cargo.toml          README.md           clippy.toml         jaeger.sh           start_all.sh
CONTRIBUTING.md     Dockerfile          TODOs.org           crates              mainnet             taker-frontend
CRATE-STRUCTURE.md  FAQ.md              TODOs.org_archive   docs                maker-frontend      target
Cargo.lock          LICENSE             bors.toml           dprint.json         rust-toolchain.toml testnet

**Comment by luckysori** [comment]
> maybe a bit more explanation: when new people get onboarded to the project, especially new to Rust, it's hard to find yourself in the project with over 30 directories in its root (especially
> 
> This way we have a logical split between:
> 
>     * rust crates
> 
>     * docs
> 
>     * target dir
> 
>     * frontend dirs
> 
>     * `mainnet`/`testnet` dirs (outcome of running the program).
> 
> 
> We had to go through each directory last time when onboarding as the present accidental structure can be confusing, and I feel that we could do better. To me this is an effortless step in the right direction (still flat structure of the crates, but they're "contained" in a single directory).
> 
> To illustrate:
> 
>     * Before
> 
> 
> ```
>   CHANGELOG.md           TODOs.org_archive      jaeger.sh              rust-toolchain.toml    xtra-bitmex-price-feed
> CONTRIBUTING.md        bdk-ext                mainnet                shared-bin             xtra-libp2p
> CRATE-STRUCTURE.md     bitmex-stream          maker                  sqlite-db              xtra-libp2p-offer
> Cargo.lock             bors.toml              maker-frontend         start_all.sh           xtra-libp2p-ping
> Cargo.toml             btsieve                model                  taker                  xtra-libp2p-rollover
> Dockerfile             clippy.toml            otel-tests             taker-frontend         xtras
> FAQ.md                 daemon                 otel-tests-macro       target
> LICENSE                daemon-tests           quiet-spans            testnet
> README.md              docs                   rocket-basicauth       tokio-extras
> TODOs.org              dprint.json            rust-embed-rocket      vergen-version
> ```
> 
>     * After
> 
> 
> ```
>   CHANGELOG.md        Cargo.toml          README.md           clippy.toml         jaeger.sh           start_all.sh
> CONTRIBUTING.md     Dockerfile          TODOs.org           crates              mainnet             taker-frontend
> CRATE-STRUCTURE.md  FAQ.md              TODOs.org_archive   docs                maker-frontend      target
> Cargo.lock          LICENSE             bors.toml           dprint.json         rust-toolchain.toml testnet
> ```

All valid points, but it doesn't come for free imo. Navigating the project gets a bit more annoying since every crate now has the `crates` prefix, which is mostly noise.

In any case, I'm not against it. It comes with the small upside that you've explained. If others are okay with the small downside then I'm happy to try it.

**Comment by klochowicz** [comment]
> All valid points, but it doesn't come for free imo. Navigating the project gets a bit more annoying since every crate now has the `crates` prefix, which is mostly noise.
> 
> In any case, I'm not against it. It comes with the small upside that you've explained. If others are okay with the small downside then I'm happy to try it.

Fair enough, I guess it depends how people are navigating - I was getting sick of trying to distinguish between `maker` and `maker-frontend` in the shell :P for the IDE, projectile with fzf on emacs and Clion will find the files just as easily.
Let's see what others think about it, no rush with this one. :-)

**Comment by Restioson** [comment]
Personally IntellIj makes this clear enough for me but I am ambivalent either way

**Comment by holzeis** [comment]
I think we could do better in structuring, but just moving everything to a crates folder doesn't help a lot. I just had a quick look at other rust github projects and found that a semantic structuring makes a lot more sense.. e.g. core, tooling, extensions, etc.

**Comment by klochowicz** [comment]
closing as per above comments there is little interest in such a reorg.

**Comment by klochowicz** [comment]
> I think we could do better in structuring, but just moving everything to a crates folder doesn't help a lot. I just had a quick look at other rust github projects and found that a semantic structuring makes a lot more sense.. e.g. core, tooling, extensions, etc.

the key difference is that we have a Rust + TypeScript project, with lots of aux files. This was an attempt to separate these from each other (e.g. `maker` and `maker-frontend` - dirs next to each other, and one is a crate, one a TS frontend). 
 On the Rust level, I would find it confusing to impose any arbitrary hierarchy, as crates occupy a single namespace.

**Pull request closed without merging**
