### PR TITLE
Rename "Accept / Reject" to "Pending" in CfdTables

### PR DESCRIPTION
**Pull request by klochowicz**
Pending is a more succinct nudge to the user that they should react with an
action to the CFDs inside these tables.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Comment by da-kami** [comment]
I am not sure I agree. This group was created so the maker sees all `Accept / Reject` CFDs that have to be actioned. `Pending` is verbose and can mean a lot of things (which is reflected in the state). 
I could not come up with a better name than `Accept / Reject`, but I don't think `Pending` is better.

**Comment by bonomat** [comment]
> I am not sure I agree. This group was created so the maker sees all `Accept / Reject` CFDs that have to be actioned. `Pending` is verbose and can mean a lot of things (which is reflected in the state). I could not come up with a better name than `Accept / Reject`, but I don't think `Pending` is better.

I talked to the person who wants to run the maker at the beginning and he said either way is fine.

**Comment by klochowicz** [comment]
> I am not sure I agree. This group was created so the maker sees all `Accept / Reject` CFDs that have to be actioned. `Pending` is verbose and can mean a lot of things (which is reflected in the state). I could not come up with a better name than `Accept / Reject`, but I don't think `Pending` is better.

The way I see it is that tabs indicate a "property" of CFDs (for grouping purposes etc), so it's more natural to use adjectives than verbs. 
Verbs, such as "accept" or "reject" would be wonderful materials for buttons that actually do the action. 

Pending is definitely less verbose (it's a whole word less on 2 occasions), but I take your point that it might be a bit ambiguous at the first glance, before you start using the app.
I think  eventually we can add some tooltips that prevent any initial ambiguities.

**Comment by da-kami** [comment]
🤷‍♂️

**Review by thomaseizinger — APPROVED** [review]
I prefer the _pending_ wording.

**Pull request merged**
