### PR TITLE
chore(deps): Bump opentelemetry-related deps

### PR DESCRIPTION
**Pull request by klochowicz**
Bump opentelemetry, opentelemetry-otlp and tracing-opentelemetry.

Update to the latest HEAD of `otel-tests` repo which has these deps bumped as well.

### CODE REVIEW

**Review by Restioson — APPROVED** [review]
LGTM! What requires protoc now ,by the way?

**Review by luckysori — COMMENTED** [review]
Can you expand on why 7a654132adc4148d83fd608848f1efa9fba4a7bc is needed?

**Comment by klochowicz** [comment]
> LGTM! What requires protoc now ,by the way?

we had this requiremet, but older version of `prost` crate provided (or tried to compile) `protoc` itself. This is not the case in the latest version.

https://github.com/tokio-rs/prost#protoc

**Comment by klochowicz** [comment]
> Can you expand on why [7a65413](https://github.com/itchysats/itchysats/commit/7a654132adc4148d83fd608848f1efa9fba4a7bc) is needed?

sure: newer version of `prost` library used as one of the depedencies stopped bundling it.

https://github.com/tokio-rs/prost#protoc

I will update the commit description.

**Pull request merged**
