### PR TITLE
Add QRCode to wallet

### LINKED ISSUE #2081: Add address Qr code
Please add Qr code of address on a wallet page for a better experience :) 

image

### PR DESCRIPTION
**Pull request by bonomat**
resolves #2081

image

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]
this is a great addition, thanks for tackling this.

one nit: would it be possible to right-align the QR code with the fields? (it would present itself better)

**Comment by bonomat** [comment]
> one nit: would it be possible to right-align the QR code with the fields? (it would present itself better)

I failed doing so 😬

**Comment by bonomat** [comment]
bors retry

**Pull request merged**
