### PR TITLE
Taker UI multiple pairs

### LINKED ISSUE #2463: Redesign Taker UI to deal with new trading pair
Approach advice: 
1. go for a simple yet usable solution first so that we can roll it out fast
2. if we are not happy with it we can think of outsourcing the design

### PR DESCRIPTION
**Pull request by bonomat**
Does not fully resolve [#2463](https://github.com/itchysats/itchysats/issues/2463). Once we have the new endpoints, this needs a bit more wiring but I think the core logic should be present.

# Desktop view

<details>
<summary style="font-size:14px">Screenshot</summary>
<p>
image
</p></details>

<details>
<summary style="font-size:14px">Video</summary>
<p>

[click me](https://photos.app.goo.gl/c4BnpdBZEBCbWZSb9)
</p></details>

# Iphone 13 view

<details>
<summary style="font-size:14px">Screenshots</summary>
<p>
image

image
</p></details>

<details>
<summary style="font-size:14px">Video</summary>
<p>

[click me](https://photos.app.goo.gl/RchmzTkX5d8r7W9J9)
</p></details>

Optional TODO: 
- [ ] imho the footer needs some more love

### CODE REVIEW

**Comment by da-kami** [comment]
Great! I gave it a try locally and I think it's a good start!

Here are some of my thoughts and some issues I found. I am happy to help tackling this together!

Here's a list of my thoughts (subject to updates :):

- I generally like the sidebar, I think it will help us store more information. The fact that it is a burger menu on mobile is OK, I think that is the common design pattern to use.
    - The maker status on the right could be 
- The `Home` feels a bit odd, maybe we could actually have `Long` and `Short` there as well. It would be a bit redundant, but I feel `Home` just does not fit.
- The drop-down is a bit hidden but probably good enough for now. I think it would be good if we could make it more present. Maybe a simple label that says `Trading Pair` on top would already help.

Below are some specific issues

---

On bigger screens the top NavBar behaves a bit weird, because it does not fill up the screen at the right.

<details>
<summary style="font-size:14px">Screenshot</summary>
<p>
image
</p></details>


---

Since I had a crack with the alerts earlier I had a look how it behaves with them and it can't really handle it.
Unfortunately the styling fixes I prepared in https://github.com/itchysats/itchysats/pull/2573 don't solve that.
The layout will need a bit of more fiddling...

<details>
<summary style="font-size:14px">Screenshot</summary>
<p>
image
</p></details>

**Comment by bonomat** [comment]
I've fixed that weird space on the right side finally :)

image

**Comment by bonomat** [comment]
@da-kami : how about `Trade` instead of `Home`?

image

**Comment by bonomat** [comment]
re 
> Since I had a crack with the alerts earlier I had a look how it behaves with them and it can't really handle it.

I gave it a try on top of this PR: 

Doesn't look too bad: 

image

**Review by da-kami — APPROVED** [review]
I like it!

**Comment by bonomat** [comment]
bors cancel

**Pull request merged**
