### PR TITLE
Add a footer with social media links

### LINKED ISSUE #518: Telegram & Twitter in the UI so people can contact us
Telegram join link: https://t.me/joinchat/ULycH50PLV1jOTI0
Twitter: https://twitter.com/itchysats

### PR DESCRIPTION
**Pull request by klochowicz**
Add Telegram, Twitter and GitHub links to ItchySats.

The footer is styled in the similar way to the header and follows the theme changes.

Fixes #518

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Can we have a screenshot in the PR? :)

**Comment by klochowicz** [comment]
> Can we have a screenshot in the PR? :)

sorry about that, UI PRs should have a screenshot indeed! coming right up. 🍸

**Comment by klochowicz** [comment]
Screen Shot 2021-11-18 at 10 13 18 am
Screen Shot 2021-11-18 at 10 13 27 am

**Review by thomaseizinger — APPROVED** [review]

**Review by da-kami — APPROVED** [review]
nice!

Love the screenshots with the connection errors 😄

**Comment by thomaseizinger** [comment]
bors retry

**Pull request merged**
