### PR TITLE
Refer to correct ID when joining orders

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@da-kami I've trimmed down the test a bit, let me know if it still conveys the right idea from your perspective.

**Comment by DeliciousHair** [comment]
Test looks good to me!

**Comment by thomaseizinger** [comment]
I verified that the test fails without the fix.

**Comment by da-kami** [comment]
> @da-kami I've trimmed down the test a bit, let me know if it still conveys the right idea from your perspective.

Like the trim down, should convey the same 👍

**Review by da-kami — APPROVED** [review]

**Pull request merged**
