### PR TITLE
All tooltips to action icons in CfdTable

### PR DESCRIPTION
**Pull request by klochowicz**
It makes it a bit easier to use, especially for newcomers

### CODE REVIEW

**Comment by klochowicz** [comment]
we could capitalise the actions, but that is probably best done with some CSS rather than in JS/TS anyway.

**Review by bonomat — APPROVED** [review]
_A drop of water on a hot stone_

Definitely better, but I think we need to invest more into this :D

**Comment by klochowicz** [comment]
> A drop of water on a hot stone

as they say it in Poland, "constant dropping wears away a stone " 🥌

**Pull request merged**
