### PR TITLE
Bump xtra to latest HEAD

### PR DESCRIPTION
**Pull request by thomaseizinger**
This version includes metrics for queued messages.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]

**Review by bonomat — APPROVED** [review]

**Comment by bonomat** [comment]
bors cancel

**Review by klochowicz — APPROVED** [review]

**Comment by thomaseizinger** [comment]
It seems my PR to our xtra fork had a bug where it doesn't compile without features, sorry about that!

**Comment by klochowicz** [comment]
> It seems my PR to our xtra fork had a bug where it doesn't compile without features, sorry about that!

all good, I'll fix the errors and update. it. marking myself as assignee.

**Pull request merged**
