### PR TITLE
Add missing entries to changelog

### PR DESCRIPTION
**Pull request by luckysori**
I've focused on my stuff because that's what I can identify. Feel free to add anything I've missed.

This PR was primarily motivated by wanting to backport the changes to the changelog in [release 0.5.5](https://github.com/itchysats/itchysats/releases/tag/0.5.5).

### CODE REVIEW

**Comment by Restioson** [comment]
Is this for 0.5.5 or the next release?

**Comment by luckysori** [comment]
> Is this for 0.5.5 or the next release?

Ahh good question! Half of these belong to 0.5.5. I'll fix it later!

**Review by da-kami — APPROVED** [review]
thanks for adding these!

**Comment by luckysori** [comment]
bors retry

**Pull request merged**
