### PR TITLE
Add C++ compiler for ARM build in build release binary workflow

### PR DESCRIPTION
**Pull request by klochowicz**
We updated this on the CI, but not for here.

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
Thanks!

**Review by Restioson — COMMENTED** [review]
I'm not 100% sure how the workflows interact and compose here, but this looks good I think :sweat_smile:

**Comment by klochowicz** [comment]
> I'm not 100% sure how the workflows interact and compose here, but this looks good I think 😅

it's all described in these yaml files - they essentially setup a build env from scratch from `ubuntu:latest`, and for every place where we build arm binary we should set it up. technically we should be able to export that common think into shared action for both CI and release workflow, but this is updated like once a year 😁

**Pull request merged**
