### PR TITLE
Release 0.5.3

### PR DESCRIPTION
**Pull request by klochowicz**
Release 0.5.3 that has the xtra fix needed to be able to reduce trace volume.
Update changelog.

### CODE REVIEW

**Comment by klochowicz** [comment]
@Restioson if you still have your local grafana tempo handy, would you be able to confirm that this indeed solves the issue? :)

**Comment by Restioson** [comment]
Indeed, I'll give it a shot now!

**Comment by klochowicz** [comment]
@luckysori do you have any idea why liquidation tests fail? they seem to failed 3 times in a row.

**Comment by Restioson** [comment]
> @Restioson if you still have your local grafana tempo handy, would you be able to confirm that this indeed solves the issue? :)

This seems to work fine with the local tempo :)

**Pull request closed without merging**
