### PR TITLE
Use single generic enum for protocol completion status

### PR DESCRIPTION
**Pull request by klochowicz**
See commit messages.

TODO: CollaborativeSettlement will come in a separate PR.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice!

Wouldn't mind squashing these commits!

**Review by luckysori — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Please hold on on merging this until I get https://github.com/itchysats/itchysats/pull/880 in.

**Comment by klochowicz** [comment]
> Please hold on on merging this until I get #880 in.

No worries :)

**Comment by klochowicz** [comment]
I've rebased it on the latest master, which made the changeset larger (needed to adopt from `NoRollover` enum).

**Review by thomaseizinger — APPROVED** [review]

**Pull request merged**
