### PR TITLE
Use musl libc for x86_64 and arm build

### PR DESCRIPTION
**Pull request by bonomat**

### CODE REVIEW

**Comment by bonomat** [comment]
Is that what you meant @thomaseizinger ?

**Review by thomaseizinger — APPROVED** [review]
Yep!

Did you test this on a fork?

**Comment by bonomat** [comment]
> Yep!
> 
> Did you test this on a fork?

it failed of course :D I'll look into it but good to know that I'm on the right track.

**Comment by klochowicz** [comment]
seems that it fails on the `ring` crate. 
Perhaps using a dedicated container (like this: https://hub.docker.com/r/ekidd/rust-musl-builder/ ) could help?
It states: 
> Basic compilation for armv7 using musl-libc. Not all libraries are supported at the moment, however

**Comment by thomaseizinger** [comment]
> it failed of course :D I'll look into it but good to know that I'm on the right track.

What did it fail with? The ring crate only needs musl-gcc. Is that not included in ubuntu's `musl-tools`? Perhaps you need `musl-dev` instead?

**Comment by klochowicz** [comment]
> > it failed of course :D I'll look into it but good to know that I'm on the right track.
> 
> What did it fail with? The ring crate only needs musl-gcc. Is that not included in ubuntu's `musl-tools`? Perhaps you need `musl-dev` instead?

Failed with the same as in this issue:
https://github.com/briansmith/ring/issues/1374

(I checked, `musl-dev` is installed alonside `musl-tools` already)

**Comment by klochowicz** [comment]
I now get only linker errors, so I guess it's some progress :)

I went past the compilation step after following various guides which sum up to the following commands:

```sh
  dpkg --add-architecture arm64
 apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user-static libc6-dev-arm64-cross gcc-aarch64-linux-gnu
  apt install musl:arm64
  export CROSS_COMPILE=aarch64-linux-gnu-

```
(note that the last command didn't work for me, it was meant for debian, and perhaps ubuntu's arm64 repos are a bit different)

Linker now fails with the following error:
```
rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtend.o" "/root/.rustup/toolchains/1.55-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crtn.o"
  = note: /usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: /hermes/target/aarch64-unknown-linux-musl/debug/deps/liblibsqlite3_sys-8bfaf4281891111b.rlib(sqlite3.o):(.data.rel.aSyscall+0xb0): undefined reference to `fcntl64'
          collect2: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: could not compile `daemon` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name maker --edition=2018 daemon/src/maker.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=268b9a0ddedaa702 -C extra-filename=-268b9a0ddedaa702 --out-dir /hermes/target/aarch64-unknown-linux-musl/debug/deps --target aarch64-unknown-linux-musl -C linker=aarch64-linux-gnu-gcc -C incremental=/hermes/target/aarch64-unknown-linux-musl/debug/incremental -L dependency=/hermes/target/aarch64-unknown-linux-musl/debug/deps -L dependency=/hermes/target/debug/deps --extern anyhow=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libanyhow-b6a81b1b5a3769f4.rlib --extern async_trait=/hermes/target/debug/deps/libasync_trait-518a40bcf0b87513.so --extern atty=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libatty-01502df229daa226.rlib --extern bdk=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libbdk-00c305116c17d17b.rlib --extern bytes=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libbytes-2e006c6bfabd1568.rlib --extern cfd_protocol=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libcfd_protocol-3ffba3e18cb5d087.rlib --extern clap=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libclap-f410c12715f30e3d.rlib --extern futures=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libfutures-feb3fd2611910c88.rlib --extern hex=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libhex-c6db8bf09c8a89fc.rlib --extern hkdf=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libhkdf-60d2b9bda61c6a09.rlib --extern libsqlite3_sys=/hermes/target/aarch64-unknown-linux-musl/debug/deps/liblibsqlite3_sys-8bfaf4281891111b.rlib --extern rand=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librand-9863ac27dfe418b2.rlib --extern reqwest=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libreqwest-d40a8e57848841a4.rlib --extern rocket=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librocket-b567bbbe7e1a1775.rlib --extern rocket_basicauth=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librocket_basicauth-ccab8253d8f67e49.rlib --extern rocket_db_pools=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librocket_db_pools-49be8e25479a6109.rlib --extern rust_embed=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librust_embed-83d497c0a152b0eb.rlib --extern rust_decimal=/hermes/target/aarch64-unknown-linux-musl/debug/deps/librust_decimal-f7bdd5b2bab9b271.rlib --extern rust_decimal_macros=/hermes/target/debug/deps/librust_decimal_macros-c1822f6999b169cf.so --extern serde=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libserde-535c461ddd97b621.rlib --extern serde_json=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libserde_json-43e27a915b954b42.rlib --extern serde_plain=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libserde_plain-902d99676df5acef.rlib --extern serde_with=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libserde_with-5e603b314ae4555a.rlib --extern sha2=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libsha2-b6e2e9591cb766da.rlib --extern sqlx=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libsqlx-ca516d438a6d8ccd.rlib --extern thiserror=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libthiserror-1ab77ea74ca0d88c.rlib --extern time=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtime-4c92b3f07fa59c45.rlib --extern tokio=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtokio-63ff4ee218638518.rlib --extern tokio_tungstenite=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtokio_tungstenite-db620293d3e3bb31.rlib --extern tokio_util=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtokio_util-8cb3f5cedca4d242.rlib --extern tracing=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtracing-8c22d653f0fe3bbb.rlib --extern tracing_subscriber=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libtracing_subscriber-958b8f8f9383e00c.rlib --extern uuid=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libuuid-8cca2163f48c1297.rlib --extern xtra=/hermes/target/aarch64-unknown-linux-musl/debug/deps/libxtra-88857f69beaaaad7.rlib -C target-feature=+crt-static -L native=/hermes/target/aarch64-unknown-linux-musl/debug/build/secp256k1-sys-2644d5ba4682be72/out -L native=/hermes/target/aarch64-unknown-linux-musl/debug/build/ring-93fa17dbb7d25e5d/out -L native=/hermes/target/aarch64-unknown-linux-musl/debug/build/libsqlite3-sys-c16888ad3579d0e1/out -L native=/hermes/target/aarch64-unknown-linux-musl/debug/build/secp256k1-zkp-sys-3c062610f21ce8c4/out` (exit status: 1)
```

From some googling, we might need to statically bundle a cross-compiled sqlite3 binary (the error might be caused by different libc6 versions, as apparently only from 2.28 the `fcntl64` exists).

I'm parking this task for now.

**Comment by bonomat** [comment]
closed in favor of #273

**Pull request closed without merging**
