### PR TITLE
Include name of actor in supervisor logs

### PR DESCRIPTION
**Pull request by thomaseizinger**
We now print things like:

```
2021-12-22 16:36:42  INFO daemon::supervisor: Spawning new instance of bitmex_price_feed::Actor
```

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
I like the solution! The only thing I was wondering is if you actually benefit from using the `ActorName` trait. Wouldn't a free function suffice?

**Comment by thomaseizinger** [comment]
> I like the solution! The only thing I was wondering is if you actually benefit from using the `ActorName` trait. Wouldn't a free function suffice?

It would but `T::name()` is shorter to call :)

**Comment by thomaseizinger** [comment]
> The only thing I was wondering is if you actually benefit from using the `ActorName` trait.

@luckysori I forgot that we had that one! Creating the name automatically and having some tests / sanity checks in place seems better to me though?
Perhaps we should move the trait to `xtra_ext` and write a bunch of tests in `lib.rs` to verify the name of several actors?

**Comment by thomaseizinger** [comment]
> > The only thing I was wondering is if you actually benefit from using the `ActorName` trait.
> 
> @luckysori I forgot that we had that one! Creating the name automatically and having some tests / sanity checks in place seems better to me though? Perhaps we should move the trait to `xtra_ext` and write a bunch of tests in `lib.rs` to verify the name of several actors?

I opened https://github.com/itchysats/itchysats/issues/952.

**Review by da-kami — APPROVED** [review]

**Pull request merged**
