### PR TITLE
Add new taker-frontend

### PR DESCRIPTION
**Pull request by 1010Tom**
-rename frontend to maker-frontend
-building maker and taker will use the respective frontend

### CODE REVIEW

**Review by scratchscratchscratchy — APPROVED** [review]
законный!

**Comment by 1010Tom** [comment]
> законный!

Gesundheit!

**Comment by itchymax** [comment]
bors retry

**Comment by itchymax** [comment]
bors ping

**Comment by itchymax** [comment]
bors ping

**Comment by itchymax** [comment]
bors ping

**Comment by 1010Tom** [comment]
bors ping

**Pull request merged**
