### PR TITLE
Fix typo in buy prompt

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
>     * Remove checkbox from close position dialog
> 
>     * Remove checkbox from confirmation buy confirmation dialog
> 
>     * Use `send` instead of `do_send` in actor tests
> 
>     * Generate seed automatically if no seed is present
> 
>     * Mock common empty handlers at test actor system startup
> 
>     * Use BXBT index for main price
> 
>     * Remove support for building old taker frontend
> 
>     * Align vite configuration of the new taker UI
> 
>     * Update README after new taker frontend rollout
> 
>     * Simplify the build release binary workflow
> 
>     * Fix typo in buy prompt.

Whilst I don't really understand this PR description, happy to merge removing the comma 😅

**Comment by thomaseizinger** [comment]
> > ```
> > * Remove checkbox from close position dialog
> > 
> > * Remove checkbox from confirmation buy confirmation dialog
> > 
> > * Use `send` instead of `do_send` in actor tests
> > 
> > * Generate seed automatically if no seed is present
> > 
> > * Mock common empty handlers at test actor system startup
> > 
> > * Use BXBT index for main price
> > 
> > * Remove support for building old taker frontend
> > 
> > * Align vite configuration of the new taker UI
> > 
> > * Update README after new taker frontend rollout
> > 
> > * Simplify the build release binary workflow
> > 
> > * Fix typo in buy prompt.
> > ```
> 
> Whilst I don't really understand this PR description, happy to merge removing the comma sweat_smile

Auto-generated by the GitHub CLI, sorry.

**Comment by klochowicz** [comment]
> > ```
> > * Remove checkbox from close position dialog
> > 
> > * Remove checkbox from confirmation buy confirmation dialog
> > 
> > * Use `send` instead of `do_send` in actor tests
> > 
> > * Generate seed automatically if no seed is present
> > 
> > * Mock common empty handlers at test actor system startup
> > 
> > * Use BXBT index for main price
> > 
> > * Remove support for building old taker frontend
> > 
> > * Align vite configuration of the new taker UI
> > 
> > * Update README after new taker frontend rollout
> > 
> > * Simplify the build release binary workflow
> > 
> > * Fix typo in buy prompt.
> > ```
> 
> Whilst I don't really understand this PR description, happy to merge removing the comma 😅

I would like to point out that we're *adding* the comma, not removing it 😉

**Review by klochowicz — APPROVED** [review]

**Comment by da-kami** [comment]
> Build failed:
> 
>     * [test_daemons (windows-latest)](https://github.com/itchysats/itchysats/runs/4184710526?check_suite_focus=true)

Windows was unhappy...

```
 running 3 tests
error: test failed, to rerun pass '--test happy_path'

Caused by:
  process didn't exit successfully: `D:\a\itchysats\itchysats\target\debug\deps\happy_path-8abfda6c87344125.exe` (exit code: 0xc0000374, STATUS_HEAP_CORRUPTION)
```

**Comment by da-kami** [comment]
bors retry

**Pull request merged**
