### PR TITLE
Update xtra to master

### PR DESCRIPTION
**Pull request by Restioson**
This includes a change which should reduce redundant span tags

### CODE REVIEW

**Review by klochowicz — APPROVED** [review]

**Comment by Restioson** [comment]
https://github.com/itchysats/itchysats/runs/7404053612?check_suite_focus=true just failed, hmm

**Comment by Restioson** [comment]
Could someone bors retry or cancel? I think it's stuck...

**Comment by klochowicz** [comment]
bors retry

**Comment by klochowicz** [comment]
bors cancel

**Pull request merged**
