### PR TITLE
Fix default quantity in UI

### LINKED ISSUE #330: If taker does not change quantity, it's 0
If taker does not change quantity, it's 0 but the UI shows default value. This makes the maker reject the order immediately as the amount is out of bounds.

### PR DESCRIPTION
**Pull request by bonomat**
@thomaseizinger : I'm not sure if I understand it correctly. Can I do https://github.com/comit-network/hermes/commit/ed2ec8eb4926c9cf27d51a4659a8a872de4ad54e or is this not allowed because I change the variable independent of what is in the state? 

Alternative solution is the second commit https://github.com/comit-network/hermes/commit/ac8d6e191cc313f46ead18a5950cb0a097966f3a

resolves #330

### CODE REVIEW

**Comment by thomaseizinger** [comment]
> @thomaseizinger : I'm not sure if I understand it correctly. Can I do [ed2ec8e](https://github.com/comit-network/hermes/commit/ed2ec8eb4926c9cf27d51a4659a8a872de4ad54e) or is this not allowed because I change the variable independent of what is in the state?
> 
> Alternative solution is the second commit [ac8d6e1](https://github.com/comit-network/hermes/commit/ac8d6e191cc313f46ead18a5950cb0a097966f3a)
> 
> resolves #330

It is not harmful but also not ideal. I would suggest renaming `quantityToShow` to something like `effectiveQuantity` and use that in the payload instead of `quantity`. I think that should also fix your problem.

**Comment by bonomat** [comment]
> > @thomaseizinger : I'm not sure if I understand it correctly. Can I do [ed2ec8e](https://github.com/comit-network/hermes/commit/ed2ec8eb4926c9cf27d51a4659a8a872de4ad54e) or is this not allowed because I change the variable independent of what is in the state?
> > Alternative solution is the second commit [ac8d6e1](https://github.com/comit-network/hermes/commit/ac8d6e191cc313f46ead18a5950cb0a097966f3a)
> > resolves #330
> 
> It is not harmful but also not ideal. I would suggest renaming `quantityToShow` to something like `effectiveQuantity` and use that in the payload instead of `quantity`. I think that should also fix your problem.

please have a look :)

**Review by thomaseizinger — APPROVED** [review]
LGTM!

**Comment by bonomat** [comment]
bors +

**Pull request merged**
