### PR TITLE
Make process_manager::Actor use send_async_safe

### LINKED ISSUE #1171: CET not published for CFD
`funding-rate` branch, commit `7af18b2e20f2fab97542545b5b1a0ec5fbc44c95`. Not sure if https://github.com/itchysats/itchysats/pull/1143 will help with this issue, reporting anyway.

I have two CFDs that were force closed in exactly the same way. Both CFDs' transactions links are displayed correctly in the UI, but only one of them actually points to a transaction on chain:

image

Left CFD:
- payout tx link: https://mempool.space/testnet/tx/c29679328be0036e33ce4ce00bf540f190537d7f4db14150cbe2065e082663c7#1 (does not exist at the time reporting)
- force tx link: https://mempool.space/testnet/tx/96ebdc46e0c3ef2ae1831002e908966c9a332d4110e84e7a2c7813b1eb3daa14 (has a 168 confirmations at the time of reporting)

Right CFD:
- payout tx link: https://mempool.space/testnet/tx/21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095#1 (has 2 confirmations at the time of reporting)
- force tx link: https://mempool.space/testnet/tx/7aa4e62b7c4ae988d7178b1d1fafa81743f1b01f9b80661d11fd9df2ba7c56bd (has a 168 confirmations at the time of reporting)

database:

image

logs:

The CFD with the missing transaction has UUID `21bd8c37-cd89-4631-877a-1c92e85447a1` and we see this in the logs upon startup:

```
2022-01-20 04:08:12 TRACE daemon::monitor: CetTimelockExpired(OrderId(Hyphenated(21bd8c37-cd89-4631-877a-1c92e85447a1))) requires confirmed with 12 blocks and we have confirmed with 166 blocks
```

However, only the CET of the other CFD was published, tx-id `21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095` - which is the one found on chain for CFD `ad8cca21-f9fb-4186-873a-239284b1f426` :

```
2022-01-20 04:08:10  INFO daemon::monitor: CET published on chain: 21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095
```

relevant logs:

```
2022-01-20 04:08:06  INFO daemon::logger: Initialized logger
2022-01-20 04:08:06  INFO taker: Running version: 0.3.1-478-g49cf7a4
2022-01-20 04:08:06  INFO taker: CFDs created with this release will settle after 24 hours
2022-01-20 04:08:06  INFO taker: Authentication details: username='itchysats' password='7975e3878cab0fefc04f155563e75124ee43421ca5ec20b1d749484b0dbd0495'
2022-01-20 04:08:06  INFO daemon::db: Opened database at /Users/dakami/CoBloX/run/hermes/taker/testnet/taker.sqlite
2022-01-20 04:08:07 TRACE daemon::auto_rollover: Checking all CFDs for rollover eligibility
2022-01-20 04:08:10  INFO daemon::monitor: CET published on chain: 21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095
2022-01-20 04:08:12 TRACE daemon::monitor: Updating status of 4 transactions
2022-01-20 04:08:12 TRACE daemon::monitor: Could not find script in own state for txid 21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095, ignoring
2022-01-20 04:08:12 TRACE daemon::monitor: Could not find script in own state for txid 21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095, ignoring
2022-01-20 04:08:12 TRACE daemon::monitor: Could not find script in own state for txid 21d546cec98b328d02f17b981d25a3fd697579a678da0be03b7f9bc4169d0095, ignoring
2022-01-20 04:08:12 DEBUG daemon::monitor: Found relevant Bitcoin transaction txid=96ebdc46e0c3ef2ae1831002e908966c9a332d4110e84e7a2c7813b1eb3daa14 status=confirmed with 166 blocks
2022-01-20 04:08:12 DEBUG daemon::monitor: Found relevant Bitcoin transaction txid=7aa4e62b7c4ae988d7178b1d1fafa81743f1b01f9b80661d11fd9df2ba7c56bd status=confirmed with 166 blocks
2022-01-20 04:08:12 TRACE daemon::monitor: CetTimelockExpired(OrderId(Hyphenated(21bd8c37-cd89-4631-877a-1c92e85447a1))) requires confirmed with 12 blocks and we have confirmed with 166 blocks
2022-01-20 04:08:12 TRACE daemon::monitor: RefundTimelockExpired(OrderId(Hyphenated(21bd8c37-cd89-4631-877a-1c92e85447a1))) requires confirmed with 216 blocks and we have confirmed with 166 blocks
2022-01-20 04:08:12 TRACE daemon::monitor: 1 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-20 04:08:12  INFO daemon::monitor: Bitcoin transaction reached monitoring target txid=96ebdc46e0c3ef2ae1831002e908966c9a332d4110e84e7a2c7813b1eb3daa14 target=confirmed with 12 blocks current=confirmed with 166 blocks
2022-01-20 04:08:12 TRACE daemon::monitor: RefundFinality(OrderId(Hyphenated(21bd8c37-cd89-4631-877a-1c92e85447a1))) requires confirmed with 1 blocks and we have unseen
2022-01-20 04:08:12 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-20 04:08:12 TRACE daemon::monitor: RefundFinality(OrderId(Hyphenated(ad8cca21-f9fb-4186-873a-239284b1f426))) requires confirmed with 1 blocks and we have unseen
2022-01-20 04:08:12 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-20 04:08:12 TRACE daemon::monitor: RefundTimelockExpired(OrderId(Hyphenated(ad8cca21-f9fb-4186-873a-239284b1f426))) requires confirmed with 216 blocks and we have confirmed with 166 blocks
2022-01-20 04:08:12 TRACE daemon::monitor: 0 subscriptions reached their monitoring target, 1 remaining for this script
2022-01-20 04:08:13 DEBUG daemon: Taker actor system ready
```

Somehow we are not publishing the CET for CFD `21bd8c37-cd89-4631-877a-1c92e85447a1`.

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by luckysori — APPROVED** [review]
I swear I reviewed this when it came out. Sorry for the wait!

**Comment by luckysori** [comment]
Shall we get this in @thomaseizinger?

**Comment by klochowicz** [comment]
> Shall we get this in @thomaseizinger?

~~I'm looking at this now, please hold off for a sec :)~~

**Review by klochowicz — APPROVED** [review]

**Pull request merged**
