### PR TITLE
Move tests into a new folder

### PR DESCRIPTION
**Pull request by Restioson**
Otherwise, they all get built individually and then again as part of a new main test target.

Related to #2581

### CODE REVIEW

**Comment by klochowicz** [comment]
this one doesn't pass the CI for some reason - is it due to `tokio::main` macro?

**Comment by Restioson** [comment]
I think I accidentally left in the `main.rs` in `tests` in the commit itself 😅

**Comment by klochowicz** [comment]
> I think I accidentally left in the `main.rs` in `tests` in the commit itself 😅

if you were using remote branches on the main repo, then I would have fixed it 😝

**Comment by Restioson** [comment]
> if you were using remote branches on the main repo, then I would have fixed it :stuck_out_tongue_closed_eyes:

I wasn't sure if I should do this or stick to my fork! Is it preferred that I push a branch in this repo?

**Comment by klochowicz** [comment]
> > if you were using remote branches on the main repo, then I would have fixed it 😝
> 
> I wasn't sure if I should do this or stick to my fork! Is it preferred that I push a branch in this repo?

I guess it's the most widely used option (because it's easier and trivial to pull someone's branch and work together). using your fork is also allowed though!

**Comment by Restioson** [comment]
I just tried, and it looks like I don't have access to push to this repo currently

**Pull request merged**
